import Navbar from "@/components/Navbar";
import "@/styles/globals.css";
import { FlightProvider } from "@/contexts/FlightContext";

export const metadata = {
	title: "flight booking app",
	description: "Generated by airline system",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<FlightProvider>
			<Navbar />
			<main className=" w-full h-full inline-block z-0 bg-light dark:bg-dark lg:px-32 md:px-16 sm:px-8 ">
				{children}
			</main>
		</FlightProvider>
	);
}
