import { Providers } from "./providers";

export const metadata = {
	title: "flight booking app",
	description: "Generated by airline system",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
}
