import '@/styles/globals.css'

export const metadata = {
  title: 'flight booking app',
  description: 'Generated by airline system',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className=" w-full h-full inline-block z-0 bg-light dark:bg-dark ">
          {children}
        </main>
      </body>
    </html>
  )
}